In [61]:
a='abcdefghholppioioiu'

In [66]:
class checkUnique():
    # with additional data structure
    def isUniqueStr(x):
        isUniqe = True
        if len(x) >128: 
            isUniqe=False
        elif len(set(x))!=len(x):
            isUniqe=False
        return isUniqe  
    # without additional data structure
    def isUniqueStr1(x):
        strset=''
        isUnique=True
        for i in range (len(x)):
            if x[i] not in strset:
                strset+=x[i]
            else:
                isUnique=False
                break
        return isUnique
            


In [ ]:
# sort the strings

In [93]:
a='abcdef'
b='acbdef'

In [94]:
a_sorted=''.join(sorted(a))
b_sorted=''.join(sorted(b))

In [95]:
a_sorted==b_sorted

True

In [120]:
Input="  Mr  Join  Smith  Join "

In [121]:
Input = Input.strip()

In [124]:
import re
a=re.split('\W+', Input)
print(a)

['Mr', 'Join', 'Smith', 'Join']


In [123]:
'20%'.join(a)

'Mr20%Join20%Smith20%Join'

In [141]:
Input1='tact Coa'
Input2='taco cat'

In [142]:
b1=''.join(sorted(Input1.lower()))
b2=''.join(sorted(Input2.lower()))
b1==b2

True

In [185]:
a='pade'
b='palef'

In [151]:
a='pale'

In [186]:
def CheckOneEdit(a,b):
    if a==b:
        isOneEdit=False
    elif len(a)==len(b):
        isOneEdit=CheckReplace(a,b)
    elif len(a)==len(b)+1:
        isOneEdit=CheckInsert(a,b)
    elif len(a)==len(b)-1:
        isOneEdit=CheckInsert(b,a)
    return isOneEdit

def CheckReplace(a,b):
    for i in range(len(a)):
        if a[i]!=b[i]:
            posi=i
            break
            
    a1=a[0:posi]+a[posi+1:]
    b1=b[0:posi]+b[posi+1:]
    return a1==b1
        
def CheckInsert(a,b):
    for i in range(len(a)):
        if a[i]!=b[i]:
            posi=i
            break
    a1=a[0:posi]+a[posi+1:]
    return a1==b  
CheckOneEdit(a,b)

False

In [214]:
str1='aabbddccccccddddeeffdddxdddssf'


In [212]:
def compress(str1):
    Compressed=''
    count=0
    for i in range(len(str1)):
        count+=1        
        if (i+1 >= len(str1)) or (str1[i]!=str1[i+1]):
            Compressed+=str1[i]
            Compressed+=str(count)
            count=0

    return Compressed if len(Compressed)<len(str1) else str1
    

In [216]:
compress(str1)

'a2b2d2c6d4e2f2d3x1d3s2f1'

In [217]:
# rotating the image

In [225]:
import numpy as np
image=np.random.rand(3,4)

In [231]:
image=(image*100).astype(int)

In [254]:
image+=-12
print(image)

[[ 72 -12  73   0]
 [ 71  54  22  39]
 [ 83  40   0  29]]


In [255]:
(image==0).astype(int).sum()

2

In [243]:
import scipy.misc as imrotate

In [245]:
misc.imrotate(image,90)

array([[  0,  32,  84, 123],
       [  0, 228, 159,  61],
       [  0,   0,  88, 158]], dtype=uint8)

In [256]:
 stack = [3, 4, 5]

In [257]:
stack.append('dog')

Given an array of integers, find if the array contains any duplicates. Your function should return true if any value appears at least twice in the array, and it should return false if every element is distinct.

In [269]:
len(set(str(a)))==len(str(a))

False

In [280]:
nums=[]
if len(str(nums))>11 or nums==[]:
    ans=False
else: 
    ans=len(set(str(nums)))==len(str(nums))

print(ans)

False


In [278]:
len()

2

In [279]:
str(nums)

'[]'

In [281]:
a="dog cat cat dog"
b='abba'

In [325]:
import re
bb=re.split('\W+',a)

In [315]:
cc=bb.sort()
print(cc)

None


In [316]:
mylist = ["b", "C", "A"]
mylist.sort()

In [321]:
bb.sort()
bb

['cat', 'cat', 'dog', 'dog']

In [292]:
LabelEncoder.LabelEncoder(bb)

TypeError: object() takes no parameters

In [331]:
sorted((e,i) for i,e in enumerate(bb))

[('cat', 1), ('cat', 2), ('dog', 0), ('dog', 3)]

In [333]:
[i[0] for i in sorted(enumerate(bb), key=lambda x:x[1])]

[1, 2, 0, 3]

In [334]:
[i[0] for i in sorted(enumerate(b), key=lambda x:x[1])]

[0]

In [348]:
b='abba'

In [347]:
b

In [349]:
enumerate(b)

In [346]:
b

In [351]:
sorted(range(len(b)), key=b.__getitem__)

[0, 3, 1, 2]

In [ ]:
sorted(range(len(b)), key=b.__getitem__)

In [352]:
bb

['dog', 'cat', 'cat', 'dog']

In [353]:
sorted(range(len(bb)), key=bb.__getitem__)

[1, 2, 0, 3]